// This file is generated by Slice Machine. Update with care!

import Posts from './Posts';
import Slug from './Slug';

export {
	Posts,
	Slug,
};

export const components = {
	posts: Posts,
	slug: Slug,
};
